"""empty message

Revision ID: b1862be98712
Revises: 74807838885e
Create Date: 2017-11-06 16:35:27.082286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1862be98712'
down_revision = '74807838885e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('create_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'create_time')
    # ### end Alembic commands ###
